### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by vegetka** [bygri/trove-downloader#1]
Hello. 

It's been 5 years. Script seems not to be working any more. Any chance for update?

**Comment by bygri** [comment]
Hi, that’s a surprise as I was using it just a few months ago. I’ll see if I can get some time to check it out again.

**Comment by vegetka** [comment]
Please. And thanks. Maybe Trove's links changed, or maybe I use it on wrong items. The result I receive is like:  

_NDP: title/A/title/1798537821 (local)
Traceback (most recent call last):
  File "E:\i\trove-downloader-master\trove.py", line 126, in <module>
    for year_data in [ndp_request(d['ndp:uri']) for d in title_data['skos:narrower']]:
TypeError: 'NoneType' object is not iterable_

**Comment by bygri** [comment]
Hello, I have just got around to testing the script and for me, it’s working fine. Could you tell me what title you are trying to download?

**Comment by vegetka** [comment]
Hi. 
I'm most interested in this link: https://nla.gov.au/nla.obj-1798538294/view
For a newspaper page: https://trove.nla.gov.au/newspaper/article/60133770
I run: python trove.py A 60133770
And receive mentioned error.

**Comment by bygri** [comment]
Hello, I saw the problem. This script is meant to download a title’s entire publication history, not a single article or page. I have looked at modifying it to allow a single issue or a single page, but haven’t found the time in the past month and can’t promise that I ever would get around to it. Trove does offer a commercial service for high-resolution images of single pages, which shouldn’t be prohibitive for a one-off. I made this script because they didn’t offer non-commercial bulk purchases.
